let time;
console.log(time);
time=34;
console.log(time);
console.log('Старт поездки. Осталось минут: ' + time);
time=time-15;
console.log('Немного сторис в соцсетях. Осталось минут: ' + time);
time=time-10;
console.log('Немного не новостей, но событий. Осталось минут: ' + time);
console.log('Вы приехали. Добро пожаловать в Москву');
